### ISSUE TITLE
Error while building "building for OSX, but linking against dylib built for iOS"

### ISSUE THREAD

**Issue by lazarev** [beeware/Python-Apple-support#45]
Xcode 9.4, MacOS 10.13.4. 

When I build python build finishes with error below:

```
compile options: '-Inumpy/core/src/private -Inumpy/core/src -Inumpy/core -Inumpy/core/src/npymath -Inumpy/core/src/multiarray -Inumpy/core/src/umath -Inumpy/core/src/npysort -I/Users/andrejlazarev/Projects/Python-Apple-support/build/macOS/python/include/python3.6m -c'
xcrun: _configtest.c
xcrun --sdk iphonesimulator clang -arch x86_64 --sysroot=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.4.sdk _configtest.o -o _configtest
clang: warning: using sysroot for 'iPhoneSimulator' but targeting 'MacOSX' [-Wincompatible-sysroot]
ld: warning: URGENT: building for OSX, but linking in object file (_configtest.o) built for iOS. Note: This will be an error in the future.
ld: building for OSX, but linking against dylib built for iOS (/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.4.sdk/usr/lib/libSystem.tbd). file '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.4.sdk/usr/lib/libSystem.tbd' for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
clang: warning: using sysroot for 'iPhoneSimulator' but targeting 'MacOSX' [-Wincompatible-sysroot]
ld: warning: URGENT: building for OSX, but linking in object file (_configtest.o) built for iOS. Note: This will be an error in the future.
ld: building for OSX, but linking against dylib built for iOS (/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.4.sdk/usr/lib/libSystem.tbd). file '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.4.sdk/usr/lib/libSystem.tbd' for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
failure.
removing: _configtest.c _configtest.o
Traceback (most recent call last):
  File "setup.py", line 394, in <module>
    setup_package()
  File "setup.py", line 386, in setup_package
    setup(**metadata)
  File "/Users/andrejlazarev/Projects/Python-Apple-support/build/iOS/packages/numpy/numpy/distutils/core.py", line 169, in setup
    return old_setup(**new_attr)
  File "/Users/andrejlazarev/Projects/Python-Apple-support/build/macOS/python/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/Users/andrejlazarev/Projects/Python-Apple-support/build/macOS/python/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/Users/andrejlazarev/Projects/Python-Apple-support/build/macOS/python/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/Users/andrejlazarev/Projects/Python-Apple-support/build/iOS/packages/numpy/numpy/distutils/command/build_ext.py", line 80, in run
    self.run_command('build_src')
  File "/Users/andrejlazarev/Projects/Python-Apple-support/build/macOS/python/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/Users/andrejlazarev/Projects/Python-Apple-support/build/macOS/python/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/Users/andrejlazarev/Projects/Python-Apple-support/build/iOS/packages/numpy/numpy/distutils/command/build_src.py", line 148, in run
    self.build_sources()
  File "/Users/andrejlazarev/Projects/Python-Apple-support/build/iOS/packages/numpy/numpy/distutils/command/build_src.py", line 159, in build_sources
    self.build_library_sources(*libname_info)
  File "/Users/andrejlazarev/Projects/Python-Apple-support/build/iOS/packages/numpy/numpy/distutils/command/build_src.py", line 294, in build_library_sources
    sources = self.generate_sources(sources, (lib_name, build_info))
  File "/Users/andrejlazarev/Projects/Python-Apple-support/build/iOS/packages/numpy/numpy/distutils/command/build_src.py", line 377, in generate_sources
    source = func(extension, build_dir)
  File "numpy/core/setup.py", line 675, in get_mathlib_info
    raise RuntimeError("Broken toolchain: cannot link a simple C program")
RuntimeError: Broken toolchain: cannot link a simple C program
make: *** [build/iOS/packages/numpy/build/temp.iphonesimulator.x86_64-3.6/libpymath.a] Error 1
```

When I try to build simple program with commands:

```
xcrun --sdk iphonesimulator clang -arch x86_64 --sysroot=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.4.sdk -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -miphoneos-version-min=8.0 -Inumpy/core/src/private -Inumpy/core/src -Inumpy/core -Inumpy/core/src/npymath -Inumpy/core/src/multiarray -Inumpy/core/src/umath -Inumpy/core/src/npysort -I/Users/andrejlazarev/Projects/Python-Apple-support/build/macOS/python/include/python3.6m -c _configtest.c

xcrun --sdk iphonesimulator clang -arch x86_64 --sysroot=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.4.sdk _configtest.o -o _configtest
```

It seems to build as expected:

```
$ ./_configtest
dyld: mach-o, but built for simulator (not macOS)
Abort trap: 6
```

What I'm doing wrong?

**Comment by freakboy3742** [comment]
It's difficult to diagnose exactly what has gone wrong without knowing exactly what it is you've done in the first place. It looks like you're building numpy; what else can you tell me about how you've generated this error?

**Comment by lazarev** [comment]
Sure. I've tried to reproduce it from the very beginning. With next steps:

1. Clone clean version of repo:
`git clone https://github.com/pybee/Python-Apple-support.git`

2. Switch to branch 3.6
`git checkout 3.6`

3. Build
`make`

Then building process stops with messages:

```
C compiler: xcrun --sdk iphonesimulator clang -arch x86_64 --sysroot=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.4.sdk -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -mios-version-min=7.0

compile options: '-Inumpy/core/src/private -Inumpy/core/src -Inumpy/core -Inumpy/core/src/npymath -Inumpy/core/src/multiarray -Inumpy/core/src/umath -Inumpy/core/src/npysort -I/Users/andrejlazarev/Projects/PAS/build/macOS/python/include/python3.6m -c'
xcrun: _configtest.c
xcrun --sdk iphonesimulator clang -arch x86_64 --sysroot=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.4.sdk _configtest.o -o _configtest
clang: warning: using sysroot for 'iPhoneSimulator' but targeting 'MacOSX' [-Wincompatible-sysroot]
ld: warning: URGENT: building for OSX, but linking in object file (_configtest.o) built for iOS. Note: This will be an error in the future.
ld: building for OSX, but linking against dylib built for iOS (/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.4.sdk/usr/lib/libSystem.tbd). file '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.4.sdk/usr/lib/libSystem.tbd' for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
clang: warning: using sysroot for 'iPhoneSimulator' but targeting 'MacOSX' [-Wincompatible-sysroot]
ld: warning: URGENT: building for OSX, but linking in object file (_configtest.o) built for iOS. Note: This will be an error in the future.
ld: building for OSX, but linking against dylib built for iOS (/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.4.sdk/usr/lib/libSystem.tbd). file '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.4.sdk/usr/lib/libSystem.tbd' for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
failure.
removing: _configtest.c _configtest.o
Traceback (most recent call last):
  File "setup.py", line 394, in <module>
    setup_package()
  File "setup.py", line 386, in setup_package
    setup(**metadata)
  File "/Users/andrejlazarev/Projects/PAS/build/iOS/packages/numpy/numpy/distutils/core.py", line 169, in setup
    return old_setup(**new_attr)
  File "/Users/andrejlazarev/Projects/PAS/build/macOS/python/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/Users/andrejlazarev/Projects/PAS/build/macOS/python/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/Users/andrejlazarev/Projects/PAS/build/macOS/python/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/Users/andrejlazarev/Projects/PAS/build/iOS/packages/numpy/numpy/distutils/command/build_ext.py", line 80, in run
    self.run_command('build_src')
  File "/Users/andrejlazarev/Projects/PAS/build/macOS/python/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/Users/andrejlazarev/Projects/PAS/build/macOS/python/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/Users/andrejlazarev/Projects/PAS/build/iOS/packages/numpy/numpy/distutils/command/build_src.py", line 148, in run
    self.build_sources()
  File "/Users/andrejlazarev/Projects/PAS/build/iOS/packages/numpy/numpy/distutils/command/build_src.py", line 159, in build_sources
    self.build_library_sources(*libname_info)
  File "/Users/andrejlazarev/Projects/PAS/build/iOS/packages/numpy/numpy/distutils/command/build_src.py", line 294, in build_library_sources
    sources = self.generate_sources(sources, (lib_name, build_info))
  File "/Users/andrejlazarev/Projects/PAS/build/iOS/packages/numpy/numpy/distutils/command/build_src.py", line 377, in generate_sources
    source = func(extension, build_dir)
  File "numpy/core/setup.py", line 675, in get_mathlib_info
    raise RuntimeError("Broken toolchain: cannot link a simple C program")
RuntimeError: Broken toolchain: cannot link a simple C program
```

You can see full build process output here: https://gist.github.com/lazarev/0c49948909b11a87f58f8df7cd7bdb91

Is there anything else I can do in my environment to reveal some useful details?

**Comment by freakboy3742** [comment]
Thanks - that helps. I'm not sure how building numpy got pulled into the main build process; that's definitely an oversight. I've just pushed an update to the 3.6 Makefile; let me know if that helps.

**Comment by lazarev** [comment]
Wow! This fixed build process. Thank you!

BTW, Am I right that numpy is unavailable now? 

I believe numpy is the very first package I need after integrating with python.

**Comment by sainikhit2k** [comment]
Hi Im currently getting the same error while compiling C programs from terminal Can You help me?

**Comment by dalcacer** [comment]
//cc @samueljohn

**Comment by sagar-garg** [comment]
> Hi Im currently getting the same error while compiling C programs from terminal Can You help me?

Me as well.

**Comment by airman00** [comment]
run this before you run `make`
`export CFLAGS='-isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk'`

Obviously replace MacOSX10.15.sdk with whatever SDK you actually have on your computer

**Comment by freakboy3742** [comment]
Closing as the original question has been answered.
