### ISSUE TITLE
No module named '_sysconfigdata_m_ios_darwin' error

### ISSUE THREAD

**Issue by Loyv99** [beeware/Python-Apple-support#52]
Hi, I downloaded a project by using "Python-3.6-iOS-support.b1" . It can run successfully with those 4 .framework files. But when I substitute them with "Python-3.6-iOS-support.b7" (four .a files in it) , it can build successfully but cannot run. The error messages are as follows:

2018-08-06 17:53:47.242895+0800 Dishuhu Malala Arkuyaya[41445:3576603] PythonHome is: /Users/loyvsteve/Library/Developer/CoreSimulator/Devices/202A2C2F-45DD-4A61-A575-477E2D757C4C/data/Containers/Bundle/Application/E967194F-3628-42D1-A963-AE523028D3E9/Dishuhu Malala Arkuyaya.app/Library/Python.framework/Resources
2018-08-06 17:53:47.245397+0800 Dishuhu Malala Arkuyaya[41445:3576603] Initializing Python runtime
Failed to import the site module
Traceback (most recent call last):
  File "/Users/loyvsteve/Library/Developer/CoreSimulator/Devices/202A2C2F-45DD-4A61-A575-477E2D757C4C/data/Containers/Bundle/Application/E967194F-3628-42D1-A963-AE523028D3E9/Dishuhu Malala Arkuyaya.app/Library/Python.framework/Resources/lib/python36.zip/site.py", line 547, in <module>
  File "/Users/loyvsteve/Library/Developer/CoreSimulator/Devices/202A2C2F-45DD-4A61-A575-477E2D757C4C/data/Containers/Bundle/Application/E967194F-3628-42D1-A963-AE523028D3E9/Dishuhu Malala Arkuyaya.app/Library/Python.framework/Resources/lib/python36.zip/site.py", line 533, in main
  File "/Users/loyvsteve/Library/Developer/CoreSimulator/Devices/202A2C2F-45DD-4A61-A575-477E2D757C4C/data/Containers/Bundle/Application/E967194F-3628-42D1-A963-AE523028D3E9/Dishuhu Malala Arkuyaya.app/Library/Python.framework/Resources/lib/python36.zip/site.py", line 285, in addusersitepackages
  File "/Users/loyvsteve/Library/Developer/CoreSimulator/Devices/202A2C2F-45DD-4A61-A575-477E2D757C4C/data/Containers/Bundle/Application/E967194F-3628-42D1-A963-AE523028D3E9/Dishuhu Malala Arkuyaya.app/Library/Python.framework/Resources/lib/python36.zip/site.py", line 258, in getusersitepackages
  File "/Users/loyvsteve/Library/Developer/CoreSimulator/Devices/202A2C2F-45DD-4A61-A575-477E2D757C4C/data/Containers/Bundle/Application/E967194F-3628-42D1-A963-AE523028D3E9/Dishuhu Malala Arkuyaya.app/Library/Python.framework/Resources/lib/python36.zip/site.py", line 248, in getuserbase
  File "/Users/loyvsteve/Library/Developer/CoreSimulator/Devices/202A2C2F-45DD-4A61-A575-477E2D757C4C/data/Containers/Bundle/Application/E967194F-3628-42D1-A963-AE523028D3E9/Dishuhu Malala Arkuyaya.app/Library/Python.framework/Resources/lib/python36.zip/sysconfig.py", line 635, in get_config_var
  File "/Users/loyvsteve/Library/Developer/CoreSimulator/Devices/202A2C2F-45DD-4A61-A575-477E2D757C4C/data/Containers/Bundle/Application/E967194F-3628-42D1-A963-AE523028D3E9/Dishuhu Malala Arkuyaya.app/Library/Python.framework/Resources/lib/python36.zip/sysconfig.py", line 584, in get_config_vars
  File "/Users/loyvsteve/Library/Developer/CoreSimulator/Devices/202A2C2F-45DD-4A61-A575-477E2D757C4C/data/Containers/Bundle/Application/E967194F-3628-42D1-A963-AE523028D3E9/Dishuhu Malala Arkuyaya.app/Library/Python.framework/Resources/lib/python36.zip/sysconfig.py", line 455, in _init_posix
ModuleNotFoundError: No module named '_sysconfigdata_m_ios_darwin'

**Comment by freakboy3742** [comment]
The support package is no longer distributed as a Framework; you will need to update your project to use the new non-framework packaging.
